/**
 * Error Codes
 *
 * Centralized error codes for programmatic error handling.
 */

export const ErrorCodes = {
    // General errors (1xxx)
    UNKNOWN_ERROR: 'E1000',
    INITIALIZATION_ERROR: 'E1001',
    CONFIGURATION_ERROR: 'E1002',
    STORAGE_ERROR: 'E1003',
    STATE_ERROR: 'E1004',

    // Parse errors (2xxx)
    PARSE_ERROR: 'E2000',
    PARSE_FILE_NOT_FOUND: 'E2001',
    PARSE_INVALID_FORMAT: 'E2002',
    PARSE_UNSUPPORTED_VERSION: 'E2003',
    PARSE_SCHEMA_INVALID: 'E2004',
    PARSE_ENCODING_ERROR: 'E2005',

    // Validation errors (3xxx)
    VALIDATION_ERROR: 'E3000',
    VALIDATION_SCHEMA_MISMATCH: 'E3001',
    VALIDATION_EXPRESSION_INVALID: 'E3002',
    VALIDATION_CONNECTION_MISSING: 'E3003',
    VALIDATION_MAP_INVALID: 'E3004',
    VALIDATION_WORKFLOW_INVALID: 'E3005',

    // Conversion errors (4xxx)
    CONVERSION_ERROR: 'E4000',
    CONVERSION_UNSUPPORTED_FEATURE: 'E4001',
    CONVERSION_MAP_FAILED: 'E4002',
    CONVERSION_EXPRESSION_FAILED: 'E4003',
    CONVERSION_WORKFLOW_FAILED: 'E4004',
    CONVERSION_CONNECTION_FAILED: 'E4005',

    // Deployment errors (5xxx)
    DEPLOYMENT_ERROR: 'E5000',
    DEPLOYMENT_AUTH_FAILED: 'E5001',
    DEPLOYMENT_RESOURCE_FAILED: 'E5002',
    DEPLOYMENT_WORKFLOW_FAILED: 'E5003',
    DEPLOYMENT_CONNECTION_FAILED: 'E5004',
    DEPLOYMENT_INTEGRATION_ACCOUNT_FAILED: 'E5005',

    // Stage transition errors (6xxx)
    STAGE_ERROR: 'E6000',
    STAGE_INVALID_TRANSITION: 'E6001',
    STAGE_EXIT_CRITERIA_NOT_MET: 'E6002',
    STAGE_ENTRY_CRITERIA_NOT_MET: 'E6003',

    // Copilot errors (7xxx)
    COPILOT_ERROR: 'E7000',
    COPILOT_NOT_AVAILABLE: 'E7001',
    COPILOT_REQUEST_FAILED: 'E7002',
    COPILOT_RESPONSE_INVALID: 'E7003',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
