apiVersion: 1
datasources:
  - name: LogicApp-SQL
    type: mssql
    url: <SQL_SERVER>:1433
    database: logicapp
    user: <SQL_USER>
    jsonData:
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      encrypt: "false"
      trustServerCertificate: true
    secureJsonData:
      password: "<SQL_PASSWORD>"
    isDefault: true
    editable: true
  - name: Prometheus-CRC
    type: prometheus
    url: <PROMETHEUS_URL>
    access: proxy
    editable: true
    jsonData:
      httpHeaderName1: "Authorization"
      tlsSkipVerify: true
      httpMethod: POST
      timeInterval: "30s"
    secureJsonData:
      httpHeaderValue1: "Bearer <PROMETHEUS_TOKEN>"
