steps:
    - script: pnpm run lint
      displayName: 'Lint'
      workingDirectory: $(working_directory)
      condition: succeeded()

    - script: pnpm run build
      displayName: 'Build'
      workingDirectory: $(working_directory)
      condition: succeeded()
