parameters:
    - name: publishVersion
      type: string

steps:
    - script: npm version ${{ parameters.publishVersion }} --no-git-tag-version --allow-same-version
      displayName: 'Update version in package.json'
      workingDirectory: $(working_directory)
      condition: succeeded()

    - task: Npm@1
      displayName: 'Package VSIX'
      inputs:
          command: custom
          customCommand: 'exec @vscode/vsce package --no-dependencies'
          workingDir: $(working_directory)
          customRegistry: useFeed
          customFeed: DevDiv/CodeToCloud
