steps:
    - task: NodeTool@0
      displayName: 'Setup Node.js'
      inputs:
          versionSpec: '20.x'
      condition: succeeded()

    - task: Npm@1
      displayName: 'Install dependencies'
      inputs:
          command: ci
          workingDir: $(working_directory)
      condition: succeeded()