apiVersion: v1
baseDomain: <set-base-domain>
metadata:
  name: <set-cluster-name>
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: <set-machine-network-cidr>
platform:
  none: {}
bootstrapInPlace:
  installationDisk: /dev/disk/by-id/<set-installation-disk>
pullSecret: '<set-pull-secret-json>'
sshKey: '<set-public-ssh-key>'
apiVIPs:
- <set-api-vip>
ingressVIPs:
- <set-ingress-vip>