/**
 * Planning Cache Service
 *
 * Manages per-flow planning result caching on disk.
 * Each flow's migration planning result (mermaid diagram, workflow mapping,
 * gap analysis, patterns, etc.) is stored as a separate JSON file under
 * `.vscode/migration/planning/` for persistence across VS Code restarts.
 *
 * @module stages/planning/PlanningCacheService
 */

import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { createHash, randomUUID } from 'crypto';
import { LoggingService } from '../../services/LoggingService';
import { PlanningBrief, PlanningPreferences } from './PlanningDecisions';
import { writePlanningJson } from './PlanningStorage';

// =============================================================================
// Planning Result Types
// =============================================================================

/**
 * A Logic Apps Standard workflow produced from analysing one source flow.
 */
export interface PlannedWorkflow {
    /** Workflow name */
    readonly name: string;

    /** Description of what this workflow does */
    readonly description: string;

    /** Trigger type (e.g., 'When a file is added', 'HTTP request', 'Recurrence') */
    readonly triggerType: string;

    /** Actions in this workflow */
    readonly actions: string[];

    /** Source artifacts that map to this workflow */
    readonly sourceArtifactIds: string[];

    /** Full Logic Apps Standard workflow.json definition */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    readonly workflowDefinition?: Record<string, any>;

    /** Per-workflow Mermaid architecture diagram */
    readonly mermaid?: string;
}

/**
 * An additional Azure component required beyond Logic Apps (e.g., Service Bus, Integration Account).
 */
export interface RequiredAzureComponent {
    /** Component name (e.g., 'Azure Service Bus') */
    readonly name: string;

    /** Type of component */
    readonly type: string;

    /** Why this component is needed */
    readonly reason: string;

    /** Configuration notes */
    readonly configNotes?: string;
}

/**
 * Full planning result for a single source flow, generated by the migration-planner agent.
 */
export interface FlowPlanningResult {
    /** Immutable finalized version; older plans are assigned a stable legacy ID when read. */
    readonly planId?: string;
    readonly preferences?: PlanningPreferences;
    readonly brief?: PlanningBrief;

    /** Flow ID this result belongs to */
    readonly flowId: string;

    /** Flow name */
    readonly flowName: string;

    /** When the plan was generated */
    readonly generatedAt: string;

    /** Mermaid diagram showing the Logic Apps target architecture */
    readonly mermaid: string;

    /** Plain-language explanation of the target architecture */
    readonly explanation: string;

    /** Logic Apps Standard workflows that this flow maps to */
    readonly workflows: PlannedWorkflow[];

    /** Additional Azure components required */
    readonly azureComponents: RequiredAzureComponent[];

    /** Connector mappings: source adapter → Logic Apps connector */
    readonly connectorMappings: {
        readonly source: string;
        readonly target: string;
        readonly isNative: boolean;
        readonly notes?: string;
    }[];

    /** Action mappings: source shape → Logic Apps action */
    readonly actionMappings: {
        readonly source: string;
        readonly target: string;
        readonly notes?: string;
        readonly workflowName?: string;
    }[];

    /** Gap analysis */
    readonly gaps: {
        readonly component: string;
        readonly gap: string;
        readonly severity: 'high' | 'medium' | 'low';
        readonly recommendation: string;
    }[];

    /** Detected integration patterns */
    readonly patterns: {
        readonly name: string;
        readonly sourceApproach: string;
        readonly logicAppsApproach: string;
        readonly complexity: 'high' | 'medium' | 'low';
    }[];

    /** Effort estimate */
    readonly effortEstimate?: {
        readonly totalHours: number;
        readonly breakdown: {
            readonly analysis: number;
            readonly conversion: number;
            readonly testing: number;
            readonly deployment: number;
        };
        readonly confidence: 'high' | 'medium' | 'low';
    };

    /** Summary notes */
    readonly summary: string;

    /** Artifact dispositions: what needs conversion and where to upload */
    readonly artifactDispositions?: {
        readonly artifactName: string;
        readonly artifactType: string;
        readonly conversionRequired: boolean;
        readonly conversionFrom?: string;
        readonly conversionTo?: string;
        readonly conversionNotes?: string;
        readonly uploadDestination:
            | 'integration-account'
            | 'logic-app-artifact-folder'
            | 'azure-function'
            | 'not-applicable';
        readonly uploadPath?: string;
        readonly uploadNotes?: string;
    }[];
}

// =============================================================================
// Planning Cache Service
// =============================================================================

const PLANNING_DIR = '.vscode/migration/planning';
const FINALIZED_PLAN_FILENAME = 'plan.json';

export class PlanningCacheService {
    private static instance: PlanningCacheService | undefined;
    private readonly logger = LoggingService.getInstance();
    private readonly cache = new Map<string, FlowPlanningResult>();
    private loaded = false;

    private constructor() {}

    public static getInstance(): PlanningCacheService {
        if (!PlanningCacheService.instance) {
            PlanningCacheService.instance = new PlanningCacheService();
        }
        return PlanningCacheService.instance;
    }

    // =========================================================================
    // Public API
    // =========================================================================

    /**
     * Store a planning result for a flow. Writes to disk immediately.
     */
    public async store(result: FlowPlanningResult): Promise<FlowPlanningResult> {
        this.ensureLoaded();
        const dir = this.getPlanningDir();
        if (!dir) {
            throw new Error('Open a workspace before finalizing a migration plan.');
        }

        const flowDir = path.join(dir, this.sanitizeFlowId(result.flowId));
        const historyDir = path.join(flowDir, 'history');
        fs.mkdirSync(historyDir, { recursive: true });
        const previous = this.cache.get(result.flowId);
        if (previous) {
            this.archive(historyDir, previous);
        }
        const finalized: FlowPlanningResult = {
            ...structuredClone(result),
            planId: randomUUID(),
            generatedAt: new Date().toISOString(),
        };
        const archivePath = this.archive(historyDir, finalized);
        try {
            writePlanningJson(path.join(flowDir, FINALIZED_PLAN_FILENAME), finalized);
        } catch (error) {
            fs.unlinkSync(archivePath);
            throw error;
        }
        this.cache.set(result.flowId, finalized);
        this.logger.debug(
            `[PlanningCache] Saved plan version "${finalized.planId}" for "${result.flowId}"`
        );
        return finalized;
    }

    /**
     * Get the cached planning result for a flow.
     * Loads from disk on first access.
     */
    public get(flowId: string): FlowPlanningResult | undefined {
        this.ensureLoaded();
        return this.cache.get(flowId);
    }

    /**
     * Check if a planning result exists for a flow.
     */
    public has(flowId: string): boolean {
        this.ensureLoaded();
        return this.cache.has(flowId);
    }

    /**
     * Get all cached planning results.
     */
    public getAll(): FlowPlanningResult[] {
        this.ensureLoaded();
        return Array.from(this.cache.values());
    }

    public getHistory(flowId: string): FlowPlanningResult[] {
        this.ensureLoaded();
        const versions = new Map<string, FlowPlanningResult>();
        const dir = this.getPlanningDir();
        const historyDir = dir && path.join(dir, this.sanitizeFlowId(flowId), 'history');
        if (historyDir && fs.existsSync(historyDir)) {
            for (const entry of fs.readdirSync(historyDir, { withFileTypes: true })) {
                if (!entry.isFile() || !entry.name.endsWith('.json')) {
                    continue;
                }
                const result = this.withVersion(
                    JSON.parse(
                        fs.readFileSync(path.join(historyDir, entry.name), 'utf-8')
                    ) as FlowPlanningResult
                );
                if (result.flowId !== flowId) {
                    throw new Error(`Plan history "${entry.name}" belongs to a different flow.`);
                }
                versions.set(result.planId, result);
            }
        }
        const current = this.cache.get(flowId);
        if (current) {
            const versioned = this.withVersion(current);
            versions.set(versioned.planId, versioned);
        }
        return [...versions.values()].sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));
    }

    public getVersion(flowId: string, planId: string): FlowPlanningResult | undefined {
        return this.getHistory(flowId).find((plan) => plan.planId === planId);
    }

    /**
     * Remove a planning result for a flow (both memory and disk).
     */
    public async remove(flowId: string): Promise<void> {
        this.cache.delete(flowId);

        const dir = this.getPlanningDir();
        if (!dir) {
            return;
        }

        // New location: planning/{flowId}/plan.json
        const flowDir = path.join(dir, this.sanitizeFlowId(flowId));
        const historyDir = path.join(flowDir, 'history');
        const filePath = path.join(flowDir, FINALIZED_PLAN_FILENAME);
        try {
            if (fs.existsSync(historyDir)) {
                fs.rmSync(historyDir, { recursive: true });
            }
            if (fs.existsSync(filePath)) {
                fs.unlinkSync(filePath);
                this.logger.debug(`[PlanningCache] Removed planning result for flow "${flowId}"`);
            }
        } catch (error) {
            this.logger.warn('[PlanningCache] Failed to remove planning result', {
                error: error instanceof Error ? error.message : String(error),
            });
        }

        // Also clean up legacy flat file if it exists
        const legacyPath = path.join(dir, `plan-${this.sanitizeFlowId(flowId)}.json`);
        try {
            if (fs.existsSync(legacyPath)) {
                fs.unlinkSync(legacyPath);
                this.logger.debug(`[PlanningCache] Removed legacy plan file for flow "${flowId}"`);
            }
        } catch {
            // ignore
        }
    }

    /**
     * Clear all cached planning results.
     */
    public async clearAll(): Promise<void> {
        this.cache.clear();

        const dir = this.getPlanningDir();
        if (!dir || !fs.existsSync(dir)) {
            return;
        }

        try {
            let removedCount = 0;
            const entries = fs.readdirSync(dir, { withFileTypes: true });

            // Remove legacy flat plan-*.json files at root
            for (const entry of entries) {
                if (entry.isFile() && entry.name.endsWith('.json')) {
                    fs.unlinkSync(path.join(dir, entry.name));
                    removedCount++;
                }
            }

            // Remove plan.json from each flow subdirectory
            for (const entry of entries) {
                if (entry.isDirectory()) {
                    const historyDir = path.join(dir, entry.name, 'history');
                    if (fs.existsSync(historyDir)) {
                        fs.rmSync(historyDir, { recursive: true });
                    }
                    const planFile = path.join(dir, entry.name, FINALIZED_PLAN_FILENAME);
                    if (fs.existsSync(planFile)) {
                        fs.unlinkSync(planFile);
                        removedCount++;
                    }
                }
            }

            this.logger.debug(
                `[PlanningCache] Cleared all planning results (${removedCount} files)`
            );
        } catch (error) {
            this.logger.warn('[PlanningCache] Failed to clear planning results', {
                error: error instanceof Error ? error.message : String(error),
            });
        }
    }

    // =========================================================================
    // Internals
    // =========================================================================

    /**
     * Ensure all existing planning results are loaded into memory.
     * Supports both legacy flat JSON files (plan-{id}.json) and the
     * new folder-based structure ({flowId}/ with individual files).
     */
    private ensureLoaded(): void {
        if (this.loaded) {
            return;
        }
        this.loaded = true;

        const dir = this.getPlanningDir();
        if (!dir || !fs.existsSync(dir)) {
            return;
        }

        try {
            const entries = fs.readdirSync(dir, { withFileTypes: true });

            // Legacy: load flat plan-*.json files at planning/ root
            const jsonFiles = entries.filter((e) => e.isFile() && e.name.endsWith('.json'));
            for (const file of jsonFiles) {
                try {
                    const content = fs.readFileSync(path.join(dir, file.name), 'utf-8');
                    const result = JSON.parse(content) as FlowPlanningResult;
                    if (result.flowId) {
                        this.cache.set(result.flowId, this.withVersion(result));
                    }
                } catch {
                    this.logger.warn(`[PlanningCache] Failed to parse ${file.name} — skipping`);
                }
            }

            // New: load finalized plan.json from flow subdirectories
            const folders = entries.filter((e) => e.isDirectory());
            for (const folder of folders) {
                const planFile = path.join(dir, folder.name, FINALIZED_PLAN_FILENAME);
                if (fs.existsSync(planFile)) {
                    try {
                        const content = fs.readFileSync(planFile, 'utf-8');
                        const result = JSON.parse(content) as FlowPlanningResult;
                        if (result.flowId) {
                            this.cache.set(result.flowId, this.withVersion(result));
                        }
                    } catch {
                        this.logger.warn(
                            `[PlanningCache] Failed to parse ${folder.name}/${FINALIZED_PLAN_FILENAME} — skipping`
                        );
                    }
                }
            }

            this.logger.debug(
                `[PlanningCache] Loaded ${this.cache.size} planning results from disk`
            );
        } catch (error) {
            this.logger.warn('[PlanningCache] Failed to load planning results from disk', {
                error: error instanceof Error ? error.message : String(error),
            });
        }
    }

    /**
     * Get the planning directory path.
     */
    private getPlanningDir(): string | undefined {
        const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
        if (!workspaceFolder) {
            return undefined;
        }
        return path.join(workspaceFolder.uri.fsPath, PLANNING_DIR);
    }

    /**
     * Sanitize a flow ID for use as a filesystem directory/file name.
     */
    private sanitizeFlowId(flowId: string): string {
        return flowId.replace(/[^a-zA-Z0-9_-]/g, '_');
    }

    private withVersion(result: FlowPlanningResult): FlowPlanningResult & { planId: string } {
        return {
            ...result,
            planId:
                result.planId ||
                `legacy-${createHash('sha256').update(JSON.stringify(result)).digest('hex')}`,
        };
    }

    private archive(historyDir: string, result: FlowPlanningResult): string {
        const version = this.withVersion(result);
        const filePath = path.join(historyDir, `${this.sanitizeFlowId(version.planId)}.json`);
        if (!fs.existsSync(filePath)) {
            writePlanningJson(filePath, version);
        }
        return filePath;
    }

    /**
     * Reset singleton (for tests).
     */
    public static resetInstance(): void {
        PlanningCacheService.instance = undefined;
    }
}
