apiVersion: 1
datasources:
  - name: LogicApp-SQL
    type: mssql
    access: proxy
    url: 10.26.1.71:1433
    database: logicapp
    user: logicappsuser
    isDefault: true
    editable: true
    jsonData:
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      encrypt: disable
      trustServerCertificate: true
    secureJsonData:
      password: ${SQL_PASSWORD}
  - name: Prometheus-Portal
    type: prometheus
    access: proxy
    editable: true
    url: https://thanos-querier-openshift-monitoring.apps.psrivasrancher.test:9091
    jsonData:
      tlsSkipVerify: true
      httpMethod: POST
      timeInterval: 30s
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: 'REPLACED_AT_RUNTIME'
  - name: LogicApps-KPI-API
    type: yesoreyeram-infinity-datasource
    uid: logicapps-kpi-api
    access: proxy
    editable: true
    jsonData:
      tlsSkipVerify: true
